# main context
worker_processes 1;
error_log /dev/stderr notice;

events {
    # events context
    worker_connections 1024;
}

http {
    # http context：server/location 未重新設定時可使用此 root
    root /usr/share/nginx/html;
    access_log /dev/stdout;

    server {
        # server context
        listen 80 default_server;
        server_name _;

        location / {
            # location context
            try_files $uri $uri/ =404;
        }
    }
}
