worker_processes 2;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    server {
        listen 80 default_server;
        server_name _;

        location / {
            default_type text/plain;
            return 200 "config version: v1\n";
        }
    }
}
