worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    upstream round_robin_pool {
        server host.docker.internal:9011;
        server host.docker.internal:9012;
    }

    upstream least_conn_pool {
        least_conn;
        server host.docker.internal:9011;
        server host.docker.internal:9012;
    }

    upstream sticky_pool {
        ip_hash;
        server host.docker.internal:9011;
        server host.docker.internal:9012;
    }

    server {
        listen 80 default_server;
        server_name _;

        location /round-robin/ {
            proxy_pass http://round_robin_pool;
        }

        location /least/ {
            proxy_pass http://least_conn_pool;
        }

        location /sticky/ {
            proxy_pass http://sticky_pool;
        }
    }
}
