worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80 default_server;
        server_name faceid.example.com;

        return 301 https://faceid.example.com$request_uri;
    }

    server {
        listen 443 ssl default_server;
        server_name faceid.example.com;

        ssl_certificate /etc/nginx/certs/faceid.example.com.crt;
        ssl_certificate_key /etc/nginx/certs/faceid.example.com.key;

        add_header X-Lab "day4-hour3-https" always;
        add_header X-Server-Name "faceid.example.com" always;

        location / {
            return 200 "secure faceid site\n";
        }
    }
}
