worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    proxy_connect_timeout 1s;
    proxy_send_timeout 1s;
    proxy_read_timeout 1s;
    client_max_body_size 64m;

    server {
        listen 80 default_server;
        server_name _;

        location = /healthy {
            proxy_pass http://host.docker.internal:9001/healthy;
        }

        location = /connect-failure {
            proxy_pass http://host.docker.internal:65534/;
        }

        location = /read-timeout {
            proxy_pass http://host.docker.internal:9001/read-timeout;
        }

        location = /send-timeout {
            proxy_http_version 1.1;
            proxy_request_buffering off;
            proxy_pass http://host.docker.internal:9002;
        }
    }
}
