worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    server {
        listen 80 default_server;
        server_name _;

        location = /buffered {
            proxy_buffering on;
            proxy_pass http://host.docker.internal:9003/stream;
        }

        location = /unbuffered {
            proxy_buffering off;
            proxy_pass http://host.docker.internal:9003/stream;
        }

        location = /header-controlled {
            proxy_buffering on;
            proxy_pass http://host.docker.internal:9003/stream-no-buffer;
        }
    }
}
