worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    server {
        listen 80 default_server;
        server_name _;
        add_header X-Selected-Server default always;
        return 200 "default site\n";
    }

    server {
        listen 80;
        server_name app.local.test;
        add_header X-Selected-Server faceid-api always;
        return 200 "FaceID API site\n";
    }
}
