worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80 default_server;

        location = /broken {
            return 200 "missing semicolon\n"
        }
    }
}
