worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    client_header_timeout 60s;
    keepalive_timeout 60s;

    server {
        listen 80 default_server;
        server_name _;

        location / {
            default_type text/plain;
            return 200 "single worker is responsive\n";
        }
    }
}
